repos:
  - repo: https://github.com/prashant0085/central-repo-git-hooks.git
    rev: master
    hooks:
      - id: check-readme
      - id: terraform-fmt
      - id: packer-validate
      - id: cfn-lint
      - id: flake8-lint
      - id: security-check
      - id: check-prtemplate
